import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import {scanModels,ggufMetadata} from '../lib/scanner.mjs';
import {buildMessages} from '../lib/prompts.mjs';
import {localURL,probe,complete,mediaParts} from '../lib/inference.mjs';

const input={script:'修表师打开怀表',mode:'cinematic',duration:10};
function u32(n){const b=Buffer.alloc(4);b.writeUInt32LE(n);return b;}
function u64(n){const b=Buffer.alloc(8);b.writeBigUInt64LE(BigInt(n));return b;}
function str(s){const b=Buffer.from(s);return Buffer.concat([u64(b.length),b]);}
function gguf(meta){return Buffer.concat([Buffer.from('GGUF'),u32(3),u64(0),u64(Object.keys(meta).length),...Object.entries(meta).flatMap(([k,v])=>[str(k),u32(typeof v==='boolean'?7:8),typeof v==='boolean'?Buffer.from([Number(v)]):str(v)])]);}
test('剧情关联关闭时完全排除历史与前情',()=>{const result=buildMessages({...input,linkContext:false,context:'禁止出现的前情',history:[{script:'旧输入',output:'旧输出'}]});assert.equal(result.length,2);assert.doesNotMatch(JSON.stringify(result),/禁止出现的前情|旧输入|旧输出/);});
test('剧情关联只带最近三轮',()=>{const result=buildMessages({...input,linkContext:true,context:'角色甲',history:[0,1,2,3].map(i=>({script:`旧镜头${i}`,output:`提示${i}`}))});assert.equal(result.length,9);assert.match(JSON.stringify(result),/角色甲|旧镜头3/);assert.doesNotMatch(JSON.stringify(result),/旧镜头0/);});
test('拒绝空输入、非法模式和时长',()=>{assert.throws(()=>buildMessages({...input,script:''}));assert.throws(()=>buildMessages({...input,mode:'invalid'}));assert.throws(()=>buildMessages({...input,duration:NaN}));});
test('本地地址校验禁止远端与非 HTTP',()=>{assert.equal(localURL('http://127.0.0.1:8080/v1'),'http://127.0.0.1:8080');for(const s of ['https://localhost','http://example.com','http://127.0.0.1.evil.com','file:///tmp/a','http://user@localhost'])assert.throws(()=>localURL(s));});
test('递归多根目录、去重、投影元数据识别、分片与异常文件',async()=>{const root=await fs.mkdtemp(path.join(os.tmpdir(),'h3-test-'));try{const sub=path.join(root,'nested');await fs.mkdir(sub);await fs.writeFile(path.join(sub,'qwen.gguf'),gguf({'general.architecture':'qwen2','general.name':'示例'}));await fs.writeFile(path.join(sub,'vision.gguf'),gguf({'general.architecture':'clip','clip.has_vision_encoder':true}));await fs.writeFile(path.join(sub,'part-00002-of-00002.gguf'),gguf({'general.architecture':'qwen2'}));await fs.writeFile(path.join(root,'broken.gguf'),'bad');await fs.writeFile(path.join(root,'model.safetensors'),'');const result=await scanModels([root,sub,path.join(root,'missing')]);assert.equal(result.models.length,5);assert.equal(result.warnings.length,1);const base=result.models.find(m=>m.name==='qwen.gguf');assert.equal(base.runnable,true);assert.equal(base.suggestions.length,1);assert.equal(result.models.find(m=>m.name==='vision.gguf').kind,'mmproj');assert.equal(result.models.find(m=>m.name==='part-00002-of-00002.gguf').runnable,false);assert.equal(result.models.find(m=>m.name==='broken.gguf').runnable,false);await assert.rejects(()=>ggufMetadata(path.join(root,'broken.gguf')));}finally{await fs.rm(root,{recursive:true,force:true});}});
test('不支持的媒体必须阻止发送，不静默丢弃',async()=>{for(const kind of ['image','audio','video'])await assert.rejects(()=>mediaParts([{kind,name:'sample',data:'AA=='}],{vision:false,audio:false},{},new AbortController().signal),/不支持/);});
test('图片和音频构造真实多模态消息',async()=>{const parts=await mediaParts([{kind:'image',name:'a.png',mime:'image/png',data:'AA==',role:'人物身份'},{kind:'audio',name:'a.wav',ext:'wav',data:'AA=='}],{vision:true,audio:true},{},new AbortController().signal);assert.equal(parts[1].type,'image_url');assert.equal(parts[3].type,'input_audio');assert.match(parts[0].text,/人物身份/);});
test('兼容服务探测与真实 HTTP 消息协议',async()=>{let received;const srv=http.createServer(async(req,res)=>{res.setHeader('Content-Type','application/json');if(req.url==='/v1/models')return res.end(JSON.stringify({data:[{id:'test-local'}]}));if(req.url==='/props')return res.end(JSON.stringify({modalities:{vision:true,audio:false}}));let chunks=[];for await(const c of req)chunks.push(c);received=JSON.parse(Buffer.concat(chunks));res.end(JSON.stringify({choices:[{message:{content:'近景，修表师打开旧怀表。'},finish_reason:'stop'}]}));});await new Promise(r=>srv.listen(0,'127.0.0.1',r));try{const endpoint=`http://127.0.0.1:${srv.address().port}`;const caps=await probe(endpoint);assert.equal(caps.vision,true);assert.equal(caps.audio,false);const result=await complete(endpoint,'test-local',buildMessages(input),{temperature:0.7,maxTokens:1000},new AbortController().signal);assert.match(result.output,/修表师/);assert.equal(received.model,'test-local');assert.equal(received.messages.length,2);}finally{await new Promise(r=>srv.close(r));}});
test('服务未声明能力时保守禁用多模态',async()=>{const srv=http.createServer((req,res)=>{if(req.url==='/props'){res.writeHead(404);return res.end();}res.end(JSON.stringify({data:[{id:'text'}]}));});await new Promise(r=>srv.listen(0,'127.0.0.1',r));try{const caps=await probe(`http://127.0.0.1:${srv.address().port}`);assert.equal(caps.known,false);assert.equal(caps.vision,false);assert.equal(caps.audio,false);}finally{await new Promise(r=>srv.close(r));}});
